# VICH UPLOADER Configuration
vich_uploader:
    db_driver: orm
    mappings:
        company_image:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/../public/uploads'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
